version: "3"
services:
  app:
    build:
      context: ./docker
      dockerfile: app.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www:cached
    environment:
      PHP_IDE_CONFIG: "serverName=gr-server"

  # The Web Server
  web:
    build:
      context: ./docker
      dockerfile: web.dockerfile
    working_dir: /var/www
    volumes:
      - ./:/var/www:cached
    ports:
      - 8080:80
    expose:
      - 9000

  # The Database
  database:
    platform: linux/x86_64
    image: mysql:5.7
    volumes:
      - gr_dbdata:/var/lib/mysql
    environment:
      - "MYSQL_DATABASE=homestead"
      - "MYSQL_USER=homestead"
      - "MYSQL_PASSWORD=secret"
      - "MYSQL_ROOT_PASSWORD=secret"
    ports:
      - "33061:3306"

  node:
    image: node:14.18
    working_dir: /var/www
    volumes:
      - ./:/var/www:cached

volumes:
  gr_dbdata:
